%YAML:1.0
Debug_mode: 1
Camera_device: 0
Resolution_camera: [ 640, 480 ]
Resolution_projector: [ 1920, 1200 ]
Fullscreen_projector: 0
Projection_top_left: [ 170., 100. ]
Projection_top_right: [ 497., 107. ]
Projection_bottom_left: [ 155., 285. ]
Projection_bottom_right: [ 504., 292. ]
Meter_camera: 6.9065185546875000e+01
Meter_projector: 4.2579348754882812e+02
Minimum_Area_Blobs: 50
Minimum_Distance_Between_Blobs: 35
Maximum_FPS_scene: 60
FPS_capture_scene: 8
Iterations_delay_peopleextracting: 0
Factor_resize_capture_scene: 10
Frames_projector_camera_delay: 0
Projector_background_light: 2.9999999329447746e-02
