%YAML:1.0
Debug_mode: 1
Camera_device: 0
Resolution_camera: [ 640, 480 ]
Projection_top_left: [ 495., 309. ]
Projection_top_right: [ 147., 301. ]
Projection_bottom_left: [ 491., 121. ]
Projection_bottom_right: [ 157., 112. ]
Meter_camera: 6.0074954986572266e+01
Resolution_projector: [ 1920, 1200 ]
Fullscreen_projector: 0
Meter_projector: 2.4965504455566406e+02
Maximum_FPS_scene: 60
Frames_projector_camera_delay: 0
Projector_background_light: 2.9999999329447746e-02
FPS_capture_scene: 8
Iterations_delay_peopleextracting: 0
Factor_resize_capture_scene: 10
