%YAML:1.0
Debug_mode: 1
Camera_device: 1
Resolution_camera: [ 1600, 900 ]
Resolution_projector: [ 1920, 1200 ]
Fullscreen_projector: 0
Projection_top_left: [ 474., 346. ]
Projection_top_right: [ 159., 339. ]
Projection_bottom_left: [ 474., 155. ]
Projection_bottom_right: [ 166., 145. ]
Meter_camera: 6.9065185546875000e+01
Meter_projector: 4.2579348754882812e+02
Minimum_Area_Blobs: 50
Minimum_Distance_Between_Blobs: 25
Maximum_FPS_scene: 60
FPS_capture_scene: 8
Iterations_delay_peopleextracting: 0
Factor_resize_capture_scene: 10
Frames_projector_camera_delay: 0
Projector_background_light: 2.9999999329447746e-02
