%YAML:1.0
Debug_mode: 1
Camera_device: 1
Resolution_camera: [ 640, 480 ]
Projection_top_left: [ 523., 398. ]
Projection_top_right: [ 200., 377. ]
Projection_bottom_left: [ 523., 220. ]
Projection_bottom_right: [ 215., 207. ]
Meter_camera: 6.0530982971191406e+01
Resolution_projector: [ 1920, 1200 ]
Fullscreen_projector: 1
Meter_projector: 2.8327456665039062e+02
Maximum_FPS_scene: 60
Frames_projector_camera_delay: 0
Projector_background_light: 2.9999999329447746e-02
FPS_capture_scene: 8
Iterations_delay_peopleextracting: 0
Factor_resize_capture_scene: 10
