%YAML:1.0
Debug_mode: 0
<<<<<<< HEAD
Camera_device: 0
Resolution_camera: [ 640, 480 ]
Projection_top_left: [ 500., 304. ]
Projection_top_right: [ 83., 304. ]
Projection_bottom_left: [ 491., 82. ]
Projection_bottom_right: [ 95., 78. ]
Meter_camera: 57.
Resolution_projector: [ 1920, 1080 ]
Fullscreen_projector: 1
Meter_projector: 2.6533520507812500e+02
=======
Camera_device: 1
Resolution_camera: [ 640, 480 ]
Projection_top_left: [ 502., 335. ]
Projection_top_right: [ 80., 338. ]
Projection_bottom_left: [ 490., 108. ]
Projection_bottom_right: [ 92., 103. ]
Meter_camera: 63.
Resolution_projector: [ 1280, 720 ]
Fullscreen_projector: 1
Meter_projector: 1.9650152587890625e+02
>>>>>>> origin/master
Maximum_FPS_scene: 60
Frames_projector_camera_delay: 0
Projector_background_light: 2.9999999329447746e-02
FPS_capture_scene: 8
Iterations_delay_peopleextracting: 0
Factor_resize_capture_scene: 10
