%YAML:1.0
Camera_device: 1
Resolution_camera: [ 640, 480 ]
Resolution_projector: [ 1024, 768 ]
Fullscreen_projector: 1
Projection_top_left: [ 297., 437. ]
Projection_top_right: [ 65., 174. ]
Projection_bottom_left: [ 473., 236. ]
Projection_bottom_right: [ 249., 24. ]
Frames_projector_camera_delay: 0
Projector_background_light: 3.7999999523162842e-01
Meter_camera: 1.9547378540039062e+02
Meter_projector: 5.9826470947265625e+02
Maximum_FPS_scene: 60
FPS_capture_scene: 8
Iterations_delay_peopleextracting: 5000
Factor_resize_capture_scene: 10
Debug_mode: 1
