%YAML:1.0
Debug_mode: 1
Camera_device: 1
Resolution_camera: [ 640, 480 ]
Projection_top_left: [ 306., 417. ]
Projection_top_right: [ 117., 155. ]
Projection_bottom_left: [ 493., 247. ]
Projection_bottom_right: [ 302., 30. ]
Meter_camera: 1.8133946228027344e+02
Resolution_projector: [ 1024, 768 ]
Fullscreen_projector: 1
Meter_projector: 5.8124182128906250e+02
Maximum_FPS_scene: 60
Frames_projector_camera_delay: 0
Projector_background_light: 3.0000000357627869e-01
FPS_capture_scene: 8
Iterations_delay_peopleextracting: 5000
Factor_resize_capture_scene: 8
