%YAML:1.0
Camera_device: 1
Resolution_camera: [ 0, 0 ]
Resolution_projector: [ 1024, 750 ]
Fullscreen_projector: 1
Projection_top_left: [297., 437.]
Projection_top_right: [65., 174.]
Projection_bottom_left: [473., 236.]
Projection_bottom_right: [249., 24.]
Frames_projector_camera_delay: 0
Projector_background_light: 3.7999999523162842e-01
Meter_camera: 1.9432962036132812e+02
Meter_projector: 5.8712823486328125e+02
Maximum_FPS_scene: 60
FPS_capture_scene: 8
Iterations_delay_peopleextracting: 5000
Factor_resize_capture_scene: 10
