%YAML:1.0
Debug_mode: 1
Camera_device: 0
Resolution_camera: [ 640, 480 ]
Projection_top_left: [ 297., 422. ]
Projection_top_right: [ 115., 170. ]
Projection_bottom_left: [ 484., 253. ]
Projection_bottom_right: [ 300., 43. ]
Meter_camera: 1.8245547485351562e+02
Resolution_projector: [ 1024, 768 ]
Fullscreen_projector: 1
Meter_projector: 5.9966638183593750e+02
Maximum_FPS_scene: 60
Frames_projector_camera_delay: 5
Projector_background_light: 39.
FPS_capture_scene: 8
Iterations_delay_peopleextracting: 5000
Factor_resize_capture_scene: 10
