%YAML:1.0
Resolution: [ 800, 600 ]
Meter: 150
TopLeftHue: [ 0, 90 ]
TopRightHue: [ 90, 180 ]
BottomRightHue : [ 180, 270 ]
BottomLeftHue: [ 270, 0 ]
SendOutDelay: 3.
SendOutSpeed: [ 0, 2 ]
TrailCap: 75
ParticipantGravity: 3.46
ParticipantAntiGravity: 0.46
ParticipantGravityRange: 2.
BystanderGravity: 10
BystanderGravityDelay: 4.
BystanderGravityRange: -2.
AlternatingGravity: 4.15
AlternatingGravityDelay: 10.
AlternatingGravityRange: -1
ProximityRange: .7
ProximityModifier: .7
SidesEnabled: 1
SpeedCap: 2.
Fade: 4
TrailThickness: .035
MixingSpeed: 3.
MixingDistance: 2.
MixingRevertTime: 1.
ExplosionAntigravity: 27.68
ExplosionGravity: 10.38
ExplosionExTime: .2
ExplosionInTime: .3
LightSourceGravity: 3.46
ColorHoleDelay: 10.
ColorHoleGravity: 3.46
ColorHoleGravityRange: .5
ColorHoleRange: .1
