%YAML:1.0
Resolution: [ 1920, 1200 ]
Meter: 2.8327456665039062e+02
Inverted: 0
TopLeftHue: [ 0, 90 ]
TopRightHue: [ 90, 180 ]
BottomRightHue : [ 180, 270 ]
BottomLeftHue: [ 270, 0 ]
SendOutDelay: 3.
SendOutSpeed: [ 0, 2 ]
TrailCap: 80
SourceHueChangeRange: 2.
ParticipantGravity: 5.46
ParticipantAntiGravity: 0.46
ParticipantGravityRange: 2.
ParticipantGravityDistance: 0.4
ParticipantMovedThreshold: 1.
ParticipantSideThreshold: 2.
BystanderGravity: 15
BystanderGravityDelay: 4.
BystanderGravityRange: -2.
AlternatingGravity: 6.15
AlternatingGravityDelay: 10.
AlternatingGravityRange: -1
ProximityRange: .7
ProximityModifier: .7
SidesEnabled: 1
SpeedCap: 3.
Fade: 4
TrailThickness: .065
MixingSpeed: 2.
MixingDistance: 3.
MixingRevertTime: 1.
MixingTrailRange: 2.
ExplosionAntigravity: 27.68
ExplosionGravity: 10.38
ExplosionExTime: .2
ExplosionInTime: .3
LightSourceGravity: 5.46
ColorHoleDelay: 100.
ColorHoleGravity: 5
ColorHoleGravityRange: 1.2
ColorHoleRange: 2
MixingEffectThickness: .05
ColorHoleEffectThickness: .03
ColorHoleEffectPeriod: .35
StarAmount: 10
StarSpeed: .10
StandingStillFadeTime: 40
InitiateTrailRange: 1.8
BystanderInitiateTrails: 10
ParticipantInitiateTrails: 10
SourceTrailAmount: 15
SourceTrailPlacementRange: .3
TrailMaxLength: 2
