%YAML:1.0
Resolution: [ 1024, 750 ]
TopLeftHue: [ 0, 90 ]
TopRightHue: [ 90, 180 ]
BottomRightHue : [ 180, 240 ]
BottomLeftHue: [ 240, 0 ]
SendOutDelay: .1
SendOutSpeed: [ 0, 100 ]
TrailCap: 200
ParticipantGravity: 300000
ParticipantAntiGravity: 10000
BystanderGravity: 300000
BystanderGravityDelay: 2.
AlternatingGravity: 300000
AlternatingGravityDelay: 5.
ProximityRange: 300
ProximityModifier: .7
SidesEnabled: 1
SpeedCap: 400
Fade: 2
TrailThickness: 7
