%YAML:1.0
Resolution: [ 1280, 720 ]
Meter: 1.9650152587890625e+02
Inverted: 0
TopLeftHue: [ 0, 90 ]
TopRightHue: [ 90, 180 ]
BottomRightHue : [ 180, 270 ]
BottomLeftHue: [ 270, 0 ]
SendOutDelay: 3.
SendOutSpeed: [ 0, 2 ]
TrailCap: 75
ParticipantGravity: 3.46
ParticipantAntiGravity: 0.46
ParticipantGravityRange: 2.
ParticipantGravityDistance: .25
BystanderGravity: 15
BystanderGravityDelay: 4.
BystanderGravityRange: -2.
AlternatingGravity: 4.15
AlternatingGravityDelay: 10.
AlternatingGravityRange: -1
ProximityRange: .7
ProximityModifier: .7
SidesEnabled: 1
SpeedCap: 2.
Fade: 8 
TrailThickness: .055
TrailMaxLength: 2
MixingSpeed: 2.
MixingDistance: 2.
MixingRevertTime: 1.
ExplosionAntigravity: 27.68
ExplosionGravity: 10.38
ExplosionExTime: .2
ExplosionInTime: .3
LightSourceGravity: 3.46
ColorHoleDelay: 120.
ColorHoleGravity: 5
ColorHoleGravityRange: 1.2
ColorHoleRange: .4
MixingEffectThickness: .05
ColorHoleEffectThickness: .03
ColorHoleEffectPeriod: .35
StarAmount: 10
StarSpeed: .10
StandingStillFadeTime: 40
