%YAML:1.0
Debug_mode: 1
Camera_device: 0
Resolution_camera: [ 640, 480 ]
Projection_top_left: [ 96., 74. ]
Projection_top_right: [ 537., 74. ]
Projection_bottom_left: [ 100., 381. ]
Projection_bottom_right: [ 541., 362. ]
Meter_camera: 100.
Resolution_projector: [ 800, 600 ]
Fullscreen_projector: 0
Meter_projector: 1.8107649230957031e+02
Maximum_FPS_scene: 60
Frames_projector_camera_delay: 0
Projector_background_light: 3.8999998569488525e-01
FPS_capture_scene: 8
Iterations_delay_peopleextracting: 5000
Factor_resize_capture_scene: 10
