%YAML:1.0
Debug_mode: 1
Camera_device: 0
Resolution_camera: [ 640, 480 ]
Resolution_projector: [ 1920, 1200 ]
Fullscreen_projector: 0
Projection_top_left: [ 100., 68. ]
Projection_top_right: [ 1100., 68. ]
Projection_bottom_left: [ 100., 600. ]
Projection_bottom_right: [ 1100., 600. ]
Frames_projector_camera_delay: 0
Projector_background_light: 3.8999998569488525e-01
Meter_camera: 100.
Meter_projector: 1.8315229797363281e+02
Maximum_FPS_scene: 60
FPS_capture_scene: 8
Iterations_delay_peopleextracting: 5000
Factor_resize_capture_scene: 10
